---
title: "CV"
---

[a pdf version](pdfs/CV_WanjiaGuo.pdf)

### Education

 - 09/2018 - present: _Graduate Student_, Psychology (Cognitive Neuroscience), University of Oregon. Advisor: __Brice Kuhl__ 

 - 08/2012–08/2016: _B.S._, Neurobiology & Psychology with honors, University of Wisconsin-Madison. Advisor: __Bradley Postle__ 

***

### Research Experience

 - 10/2017–08/2018: _Research Assistant_, Mormino Lab. Neurology Department, Stanford University. PI: __Elizabeth Mormino__

 - 10/2016–08/2018: _Research Assistant_, Stanford Memory Lab. Psychology Department, Stanford University. PI: __Anthony Wagner__

 - 01/2015–08/2016: _Undergraduate Research Assistant_, PostLab. Departments of Psychology and Psychiatry, UW-Madison. PI: __Bradley Postle__

 - 04/2014–08/2016: _Undergraduate Research Assistant_, Wisconsin National Primate Research Center. Department of Pediatrics, UW-Madison. PI: __Ei Terasawa__

***

### Publications

 - Jiang, J., Wang, S. F., __Guo, W.__, & Wagner, A. D. (in preparation). Proactive control in context: Context-cued predictions of task demands facilitate perceptual decisions in virtual environments.

***

### Conference Presentations

 - Harrison, M., Bernstein, J., Carr, V.A., Corsol, N., Deutsch, G., Fredericks, C., Guerin, S., __Guo, W.__, Hunt, M., Jayakumar, M., Jiang, J., Kerchner, G., Khazenzon, A., Litovsky, C., Mormino, E. C., Nadiadwala, A., Sha, S., Tanner, N., Thieu, M., Trelle, A.N., Wagner, A. D. (2019). Individual differences in neural pattern similarity during encoding relate to memory performance in putatively healthy older adults. _Dallas Aging and Cognition Conference, Dallas, TX._


 - Trelle, A.N., Bernstein, J., Carr, V.A., Corsol, N., Deutsch, G., Fredericks, C., Guerin, S., __Guo, W.__, Harrison, M., Hunt, M., Jayakumar, M., Jiang, J., Kerchner, G., Khazenzon, A., Litovsky, C., Mormino, E. C., Nadiadwala, A., Sha, S., Tanner, N., Thieu, M., Wagner, A. D. (2019). Cortical differentiation, hippocampal integrity, and amzyloid burden are linked to individual differences in episodic memory decline with age. _Dallas Aging and Cognition Conference, Dallas, TX._


 - Mormino, E.C., __Guo, W.__, Nadiadwala, A., Hall, J., Trelle, A. N., Sha, S., Fredericks, C. A., Greicius, M. D., Srinivas, S. M., James, M. L., Zaharchuk, G., Wagner, A. D., Chin, F. T. (2018). Tau PET imaging with PI2620 in aging and Alzheimer’s disease. _2018 annual meeting of the SfN, San Diego, CA._


 - Jiang, J., Wang, S. F., __Guo, W.__, Wagner, A. (2018). Context-cued Predictions of Task Demands Facilitate Perceptual Decisions in Virtual Environments. _2018 annual meeting of the SfN, San Diego, CA._


 - Mormino, E.C., Nadiadwala, A., Azevedo, C., __Guo, W.__, Hall, J., Trelle, A. N., Sha, S., Fredericks, C. A., Greicius, M. D., Srinivas, S. M., James, M. L., Zaharchuk, G., Wagner, A. D., Chin, F. T. (2018). Tau PET imaging with PI2620 in aging and Alzheimer’s disease. _AAIC 2018, Chicago, IL._


 - Trelle, A.N., Bernstein, J., Harrison, M., Carr, V.A., Fredericks, C., Guerin, S., __Guo, W.__, Jayakumar, M., Jiang, J., Kerchner, G., Khazenzon, A., Litovsky, C., Mormino, E. C., Nadiadwala, A., Sha, S., Tanner, N., Thieu, M., Wagner, A. D. (2018). The Contribution of Early Alzheimer’s Disease Markers to Individual Differences in Episodic Memory in Cognitively Normal Older Adults. _AAIC 2018, Chicago, IL._


 - Trelle, A., Carr, V. A., Guerin, S., __Guo, W.__, Harrison, M. B., Jayakumar, M., Jiang, J., Kerchner, G., Momino, E. C., Tanner, N., Thieu, M., & Wagner, A.D. (2018). Parietal and occipitotemporal cortical reinstatement differentially predict successful associative memory retrieval in older adults. _Annual Meeting of the Cognitive Neuroscience Society, Boston, MA._


 - Trelle, A.N., Bernstein, J., Carr, V.A., Fredericks, C., Guerin, S., __Guo, W.__, Jayakumar, M., Jiang, J., Kerchner, G., Khazenzon, A., Litovsky, C., Sha, S., Thieu, M., Wagner, A. D. (2018). Cortical representations during memory encoding and retrieval predict successful associative memory retrieval in healthy older adults. _International Conference on Learning & Memory at UC Irvine, Huntington Beach, CA._


 - Trelle, A.N., Bernstein, J., Carr, V.A., Fredericks, C., Guerin, S., __Guo, W.__, Jayakumar, M., Jiang, J., Kerchner, G., Khazenzon, A., Litovsky, C., Sha, S., Thieu, M., Wagner, A. D. (2017). Cortical and hippocampal predictors of individual differences in episodic memory in putatively healthy older adults. _2017 annual meeting of the SfN, Washington DC._


 - __Guo, W.__, Kenealy, B., Terasawa, E. (2016). The role of MKRN3 in puberty: use of a high molecular cut off microdialysis probe. _Undergraduate Symposium, University of Wisconsin-Madison, WI._


 - __Guo, W.__, Kenealy, B., Terasawa, E. (2015). The possible relationship among GnRH, MKRN3, and puberty. _Undergraduate Symposium, University of Wisconsin-Madison, WI._

***

### Awards and Honors

 - 2018      Promising Scholar Award\
 - 2016      Undergraduate Research Scholar Award 